### ISSUE TITLE
Relationship's should not have more than one Type.

### ISSUE THREAD

**Issue by zarthross** [mrkaspa/Neo4S#1]
NeoRel and NeoNode both extends Labelable which allows for multiple labels, however Neo4j's Relationships do not have 'labels' they 'types' and can only have ONE type.  Should consider changing the hierarchy here to reflect the distinction.

**Comment by mrkaspa** [comment]
Done in the version 1.4.0

**Comment by zarthross** [comment]
Not quite what I had in mind.... I was meaning something more like this:

     trait Labelable {
      val labels: Set[String]

      private[orm]
      def labelsString(): String = {
        labels.mkString(":", ":", "")
      }
    }

    trait Typeable {
      val `type`: String
    }
